steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/catanatron-server:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/catanatron-server:latest'
      - '-f'
      - 'Dockerfile.web'
      - '.'

  # Step 2: Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/catanatron-server:$COMMIT_SHA'

  # Step 3: Push the latest tag
  - name: 'gcr.io/cloud-builders/docker'
    id: PushLatest
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/catanatron-server:latest'

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'catan-epq'
      - '--image'
      - 'gcr.io/$PROJECT_ID/catanatron-server:$COMMIT_SHA'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--port'
      - '5001'
      - '--allow-unauthenticated'

# Use Cloud Logging only (required when using a custom service account)
options:
  logging: CLOUD_LOGGING_ONLY

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/catanatron-server:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/catanatron-server:latest'
